const mainCardData = [
    {
        f1_name : "Rose Namajunas",
        f2_name : "Tracy Cortez",
        f1_age : "32",
        f1_height : "5'5",
        f1_weight : "134",
        f1_reach : "65\"",
        f2_age : "30",
        f2_height : "5'5",
        f2_weight : "143",
        f2_reach : "65.5\"",
        f1_image : "NAMAJUNAS_ROSE_L_07-13.png",
        f2_image : "CORTEZ_TRACY_L_09-16.png",
        line: 4.5,
        over_odds: "-315",
        under_odds: "+230",
        format: 5
    },

    {
        f1_name : "Santiago Ponzinibbio",
        f2_name : "Muslim Salikhov",
        f1_age : "37",
        f1_height : "6'0",
        f1_weight : "170",
        f1_reach : "73\"",
        f2_age : "40",
        f2_height : "5'11",
        f2_weight : "187",
        f2_reach : "70\"",
        f1_image : "PONZINIBBIO_SANTIAGO_L_07-13.png",
        f2_image : "SALIKHOV_MUSLIM_L_02-03.png",
        line: 2.5,
        over_odds: "+100",
        under_odds: "-130",
        format: 3
    },

    {
        f1_name : "Drew Dober",
        f2_name : "Jean Silva",
        f1_age : "35",
        f1_height : "5'8",
        f1_weight : "170",
        f1_reach : "70\"",
        f2_age : "27",
        f2_height : "5'7",
        f2_weight : "147.5",
        f2_reach : "69\"",
        f1_image : "DOBER_DREW_L_07-13.png",
        f2_image : "SILVA_JEAN_L_05-04.png",
        line: 1.5,
        over_odds: "-135",
        under_odds: "+105",
        format: 3
    },

    {
        f1_name : "Gabriel Bonfim",
        f2_name : "Ange Loosa",
        f1_age : "26",
        f1_height : "6'1",
        f1_weight : "170",
        f1_reach : "72.5\"",
        f2_age : "31",
        f2_height : "5'10",
        f2_weight : "183.5",
        f2_reach : "74\"",
        f1_image : "BONFIM_GABRIEL_L_07_25.png",
        f2_image : "LOOSA_ANGE_L_09-02.png",
        line: 1.5,
        over_odds: "-166",
        under_odds: "+130",
        format: 3
    },

    {
        f1_name : "Julian Erosa",
        f2_name : "Christian Rodriguez",
        f1_age : "34",
        f1_height : "6'1",
        f1_weight : "162.5",
        f1_reach : "74.5\"",
        f2_age : "26",
        f2_height : "5'7",
        f2_weight : "159",
        f2_reach : "71.5\"",
        f1_image : "EROSA_JULIAN_L_07-13.png",
        f2_image : "RODRIGUEZ_CHRISTIAN_L_03-16.png",
        line: 2.5,
        over_odds: "-145",
        under_odds: "+114",
        format: 3
    },
    {
        f1_name : "Abdul Razak Alhassan",
        f2_name : "Cody Brundage",
        f1_age : "38",
        f1_height : "5'10",
        f1_weight : "198",
        f1_reach : "73\"",
        f2_age : "30",
        f2_height : "6'1",
        f2_weight : "202",
        f2_reach : "72\"",
        f1_image : "ALHASSAN_ABDUL_L_07-13.png",
        f2_image : "BRUNDAGE_CODY_L_04-13.png",
        line: 1.5,
        over_odds: "+124",
        under_odds: "-160",
        format: 3
    }
]


export default mainCardData;